services:
  nuage-db:
    ports:
      - "5432:5432"

  nuage-minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  nuage-api:
    ports:
      - "4000:4000"

  nuage-client:
    ports:
      - "3000:3000"
