package files

import documentation "github.com/FacileStudio/Nuage/apps/api/internal/documentation"

var Documentation = documentation.Module{
	Name:        "files",
	Description: "File and folder management routes.",
	Routes: []documentation.Route{
		{
			Method:       "POST",
			Path:         "/files",
			Summary:      "Upload a file",
			Description:  "Uploads a file via multipart form data with optional metadata.",
			Auth:         "bearer token required",
			RequestBody:  "multipart/form-data with file, folder_id, origin_app",
			ResponseBody: "FileResponse",
			Errors: []documentation.Error{
				{Status: 400, Code: "invalid_argument", Description: "Missing file or invalid metadata."},
				{Status: 401, Code: "unauthenticated", Description: "Authorization header is missing or invalid."},
				{Status: 404, Code: "not_found", Description: "Target folder does not exist."},
				{Status: 413, Code: "resource_exhausted", Description: "File is too large."},
				{Status: 500, Code: "internal", Description: "Unexpected server error."},
			},
		},
		{
			Method:       "GET",
			Path:         "/files",
			Summary:      "List files",
			Description:  "Returns files filtered by folder_id, search, linked_to, or origin_app.",
			Auth:         "bearer token required",
			ResponseBody: "FileListResponse",
		},
		{
			Method:       "GET",
			Path:         "/files/{id}",
			Summary:      "Get file metadata",
			Description:  "Returns metadata for a single file.",
			Auth:         "bearer token required",
			ResponseBody: "FileResponse",
		},
		{
			Method:      "GET",
			Path:        "/files/{id}/download",
			Summary:     "Download a file",
			Description: "Redirects to a presigned download URL.",
			Auth:        "bearer token required",
		},
		{
			Method:      "DELETE",
			Path:        "/files/{id}",
			Summary:     "Delete a file",
			Description: "Removes the file from storage and database.",
			Auth:        "bearer token required",
		},
		{
			Method:       "PUT",
			Path:         "/files/{id}",
			Summary:      "Update file metadata",
			Description:  "Rename or move a file to a different folder.",
			Auth:         "bearer token required",
			RequestBody:  "UpdateFileRequest",
			ResponseBody: "FileResponse",
		},
		{
			Method:       "POST",
			Path:         "/files/{id}/link",
			Summary:      "Link file to external entity",
			Description:  "Associates a file with an external facile_id.",
			Auth:         "bearer token required",
			RequestBody:  "LinkFileRequest",
			ResponseBody: "FileResponse",
		},
		{
			Method:       "POST",
			Path:         "/files/{id}/presign",
			Summary:      "Generate a presigned download URL",
			Description:  "Returns a time-limited, pre-authenticated URL for downloading the file without auth headers.",
			Auth:         "bearer token required",
			RequestBody:  "PresignRequest (optional expires_in in seconds, default 3600, max 604800)",
			ResponseBody: "PresignResponse",
			Errors: []documentation.Error{
				{Status: 400, Code: "invalid_argument", Description: "expires_in out of range."},
				{Status: 401, Code: "unauthenticated", Description: "Authorization header is missing or invalid."},
				{Status: 404, Code: "not_found", Description: "File does not exist."},
			},
		},
		{
			Method:       "POST",
			Path:         "/folders",
			Summary:      "Create a folder",
			Description:  "Creates a new folder with an optional parent.",
			Auth:         "bearer token required",
			RequestBody:  "CreateFolderRequest",
			ResponseBody: "FolderResponse",
		},
		{
			Method:       "GET",
			Path:         "/folders",
			Summary:      "List folders",
			Description:  "Returns folders filtered by parent_id (root if omitted).",
			Auth:         "bearer token required",
			ResponseBody: "FolderListResponse",
		},
		{
			Method:       "GET",
			Path:         "/folders/{id}",
			Summary:      "Get folder with contents",
			Description:  "Returns folder metadata plus child files and subfolders.",
			Auth:         "bearer token required",
			ResponseBody: "FolderDetailResponse",
		},
		{
			Method:       "PUT",
			Path:         "/folders/{id}",
			Summary:      "Rename or move a folder",
			Description:  "Updates folder name and/or parent.",
			Auth:         "bearer token required",
			RequestBody:  "UpdateFolderRequest",
			ResponseBody: "FolderResponse",
		},
		{
			Method:      "DELETE",
			Path:        "/folders/{id}",
			Summary:     "Delete a folder",
			Description: "Removes a folder. Must be empty.",
			Auth:        "bearer token required",
		},
	},
}
